services:
    app:
      build:
          context: .
          dockerfile: backend/Dockerfile
      command: uvicorn backend.app:app --host 0.0.0.0 --port 13789
      restart: unless-stopped
      ports:
        - "13789:13789"
